hugo: remove symlink to use the mounts module (#91)
* hugo: remove symlink to use the mounts module

It has been done to have better `watch` of `assets` in hugo (Javascript
components)

- https://github.com/lobopraveen/praveenlobo.com/issues/74
  - Especially https://github.com/lobopraveen/praveenlobo.com/issues/74#issuecomment-1669882617

As well as a fix to the following error (#90):
```
Error: Error copying static files: symlinks not allowed in this filesystem
```

* hugo: remove missing symlinks

- `corpus/` and `layouts/`